export const CHAMPION_PREDICTION_DEADLINE = new Date('2026-07-04T00:00:00-03:00');
export const CHAMPION_PREDICTION_POINTS = 500;

export const CHAMPION_TEAMS = [
  'África do Sul',
  'Alemanha',
  'Arábia Saudita',
  'Argentina',
  'Austrália',
  'Bélgica',
  'Brasil',
  'Canadá',
  'Chile',
  'Colômbia',
  'Coreia do Sul',
  'Costa Rica',
  'Croácia',
  'Dinamarca',
  'Egito',
  'Equador',
  'Espanha',
  'Estados Unidos',
  'França',
  'Gana',
  'Holanda',
  'Inglaterra',
  'Irã',
  'Itália',
  'Japão',
  'Marrocos',
  'México',
  'Nigéria',
  'Paraguai',
  'Peru',
  'Polônia',
  'Portugal',
  'Senegal',
  'Suíça',
  'Uruguai',
  'A1',
  'A2',
  'A3',
  'A4',
  'B1',
  'B2',
  'B3',
  'B4',
  'C1',
  'C2',
  'C3',
  'C4',
];

export function isChampionPredictionClosed(now = new Date()) {
  return now.getTime() >= CHAMPION_PREDICTION_DEADLINE.getTime();
}
